services:
  db:        
    build: ./MariaDB/
    container_name: db    
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: my_database
      MYSQL_USER: pepe
      MYSQL_PASSWORD: pepe
    ports:
      - "3306:3306"
    volumes: 
        - db_vol:/var/lib/mysql
        - "./log/db:/var/log"       

  phpmyadmin:    
    image: phpmyadmin 
    container_name: phpmyadmin   
    ports:
      - "8080:80"
    environment:        
        PMA_ARBITRAY: 1

  web:
      depends_on:
        - db      
      build: .
      container_name: php
      ports:
      - "80:80"
      extra_hosts:
        - "host.docker.internal:host-gateway"
      tty: true
      volumes: 
        - "./:/var/www"
        - ./docker-php-ext-xdebug.ini:/usr/local/etc/php/php.ini 
        - "./log/apache:/var/log/apache2"
        - "./log/php:/srv/var/log"
volumes:
  db_vol:    
